# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gearman-ruby}
  s.version = "3.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Ewart", "Colin Curtin", "Daniel Erat", "Ladislav Martincik", "Pablo Delgado", "Mauro Pompilio", "Antonio Garrote", "Kim Altintop"]
  s.date = %q{2012-05-24}
  s.description = %q{Library for the Gearman distributed job system}
  s.email = %q{gearman.ruby@librelist.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "TODO"
  ]
  s.files = [
    "HOWTO",
    "LICENSE",
    "README",
    "Rakefile",
    "TODO",
    "VERSION.yml",
    "examples/calculus_client.rb",
    "examples/calculus_worker.rb",
    "examples/client.php",
    "examples/client.rb",
    "examples/client_background.rb",
    "examples/client_data.rb",
    "examples/client_epoch.rb",
    "examples/client_exception.rb",
    "examples/client_prefix.rb",
    "examples/client_reverse.rb",
    "examples/gearman_environment.sh",
    "examples/scale_image.rb",
    "examples/scale_image_worker.rb",
    "examples/server.rb",
    "examples/worker.rb",
    "examples/worker_data.rb",
    "examples/worker_exception.rb",
    "examples/worker_prefix.rb",
    "examples/worker_reverse_string.rb",
    "examples/worker_reverse_to_file.rb",
    "examples/worker_signals.rb",
    "lib/gearman.rb",
    "lib/gearman/client.rb",
    "lib/gearman/server.rb",
    "lib/gearman/task.rb",
    "lib/gearman/taskset.rb",
    "lib/gearman/testlib.rb",
    "lib/gearman/util.rb",
    "lib/gearman/worker.rb",
    "test/client_test.rb",
    "test/mock_client_test.rb",
    "test/mock_worker_test.rb",
    "test/util_test.rb",
    "test/worker_test.rb"
  ]
  s.homepage = %q{http://github.com/gearman-ruby/gearman-ruby}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Library for the Gearman distributed job system}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

