$LOAD_PATH.unshift("../lib")
require 'rubygems'
require 'gearman'

# Control logger
l = Logger.new($stdout)
l.level = Logger::DEBUG
Gearman.logger=l

servers = ['localhost:4730']
  
client = Gearman::Client.new(servers)

# Submitting work with no explicit unique ID will
# cause one to be generated by the client based on
# the job queue and the data, these 10 jobs should
# get de-duped into one job in the server (provided
# that nobody is pulling from the queue in the middle)
(0..10).each do |i|
  task = Gearman::BackgroundTask.new('dedupe', 'data')
  client.do_task(task)
end
